[package]
name = "backend"
version = "0.1.0"
authors = ["Anton <antonoutkine@gmail.com>"]
edition = "2018"

[dependencies]
logic = { path = "../../logic" }

serde = { version = "1.0" }
serde_json = "1.0"

thiserror = "1.0"
